app = 'project-mgt-app'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']
  
  [[http_service.checks]]
    grace_period = "45s"
    interval = "30s"
    timeout = "10s"
    method = "get"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  GUNICORN_WORKERS = "1"
  GUNICORN_THREADS = "1"
  MALLOC_ARENA_MAX = "2"
  PYTHONOPTIMIZE = "1"
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"