"""reset clean schema

Revision ID: 1736840ec647
Revises: 
Create Date: 2026-04-15 17:27:37.822965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1736840ec647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_media_file')
    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_type'), ['project_type'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('progress',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_task_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)
        batch_op.create_foreign_key(None, 'team_member', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_team_member_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_member_invite_token'), ['invite_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_invite_token'))
        batch_op.drop_index(batch_op.f('ix_team_member_email'))
        batch_op.drop_column('joined_at')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_name'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('planned_cost')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_type'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('_alembic_tmp_media_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('filepath', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
